package:
    name: elog
    version: "{{ load_setup_py_data().version }}"
source:
    path: ..

build:
    noarch: python
    script: {{ PYTHON }} -m pip install . -vv

requirements:
    build:
        - python
        - passlib
        - requests
        - lxml

    run:
        - python
        - passlib
        - requests
        - lxml

about:
    home: https://github.com/paulscherrerinstitute/py_elog
    summary: "Interface to electronic logbooks elog."
